"""Second migration.

Revision ID: 64191fb6f94c
Revises: 7065ad3c8d53
Create Date: 2023-03-23 22:14:50.974742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64191fb6f94c'
down_revision = '7065ad3c8d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('address', sa.String(length=75), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('address')
    # ### end Alembic commands ###
